// Localidades de Granada
export const GRANADA_LOCATIONS = [
  "Fuera de Granada",
  "---", // Separador
  "Alamedilla",
  "Albolote",
  "Alcudia de Guadix",
  "Aldeire",
  "Alfacar",
  "Algarinejo",
  "Alhama de Granada",
  "Alhendín",
  "Alicún de Ortega",
  "Almegíjar",
  "Almuñécar",
  "Alquife",
  "Arenas del Rey",
  "Armilla",
  "Atarfe",
  "Baza",
  "Beas de Granada",
  "Beas de Guadix",
  "Benalúa",
  "Benalúa de las Villas",
  "Benamaurel",
  "Bérchules",
  "Bubión",
  "Busquístar",
  "Cacín",
  "Cádiar",
  "Cájar",
  "Calahorra la Vieja",
  "Calicasas",
  "Campotéjar",
  "Caniles",
  "Cáñar",
  "Capileira",
  "Carataunas",
  "Cástaras",
  "Castilléjar",
  "Castril",
  "Cenes de la Vega",
  "Chauchina",
  "Chimeneas",
  "Cijuela",
  "Cogollos de Guadix",
  "Cogollos de la Vega",
  "Cortes de Baza",
  "Cortes y Graena",
  "Cúllar",
  "Cúllar Vega",
  "Darro",
  "Dehesas de Guadix",
  "Deifontes",
  "Dílar",
  "Dólar",
  "Dúrcal",
  "Escúzar",
  "Ferreira",
  "Fonelas",
  "Fontanar",
  "Fornes",
  "Freila",
  "Fuente Vaqueros",
  "Gabias (Las)",
  "Galera",
  "Gobernador",
  "Gójar",
  "Gor",
  "Gorafe",
  "Granada",
  "Guadahortuna",
  "Guadix",
  "Güejar Sierra",
  "Güevéjar",
  "Huélago",
  "Huéneja",
  "Huéscar",
  "Illora",
  "Itrabo",
  "Iznalloz",
  "Jayena",
  "Jerez del Marquesado",
  "Jete",
  "Jun",
  "Juviles",
  "Láchar",
  "Lanjarón",
  "Lanteira",
  "Lecrín",
  "Lentegí",
  "Lobras",
  "Loja",
  "Lugros",
  "Lújar",
  "Maracena",
  "Marchal",
  "Moclín",
  "Monachil",
  "Montefrío",
  "Montejícar",
  "Montillana",
  "Moraleda de Zafayona",
  "Morelábor",
  "Motril",
  "Murtas",
  "Nigüelas",
  "Nova",
  "Ogíjares",
  "Orce",
  "Órgiva",
  "Otívar",
  "Padul",
  "Pampaneira",
  "Pedro Martínez",
  "Peligros",
  "Peza (La)",
  "Píñar",
  "Pinos Genil",
  "Pinos Puente",
  "Polícar",
  "Polopos",
  "Pórtugos",
  "Puebla de Don Fadrique",
  "Pulianas",
  "Purullena",
  "Quéntar",
  "Rubite",
  "Salar",
  "Salobreña",
  "Santa Cruz del Comercio",
  "Santa Fe",
  "Soportújar",
  "Sorvilán",
  "Taha (La)",
  "Torre-Cardela",
  "Torvizcón",
  "Trevélez",
  "Turón",
  "Ugíjar",
  "Válor",
  "Vélez de Benaudalla",
  "Ventas de Huelma",
  "Villa de Otura",
  "Villamena",
  "Villanueva de las Torres",
  "Villanueva Mesía",
  "Víznar",
  "Zafarraya",
  "Zagra",
  "Zubia (La)",
  "Zújar"
];

export default GRANADA_LOCATIONS;